# Bump the version of the repo and push the new version in a new commit.

name: Bump version

on:
  workflow_call:
    outputs:
      new_ver:
        description: New version number
        value: ${{ jobs.bump-version.outputs.new_ver }}


jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    outputs:
      new_ver: ${{ steps.bumper.outputs.new_ver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.TOKEN_GITHUB_SECRET_KEY}}
      - name: Bump version and push tag
        id: bumper
        uses: jasonamyers/github-bumpversion-action@v1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
