name: Bump version
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bumper.outputs.new_ver }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        id: bumper
        uses: jaumann/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.token }}
