# Shortcut to run the following:
# * bump-version.yml
# * Publish the python package
# * Create a release in github
# * docker-release-only.yml

name: Bump version and auto-release
on:
  workflow_call:
    secrets:
      token:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      image_base_name:
        required: true
        type: string
      docker_file:
        required: false
        type: string
        default: Dockerfile

jobs:
  bump-version:
    uses: openclimatefix/.github/.github/workflows/bump-version.yml@v1.1.0

  build:
    needs: [bump-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.token }}

  python-release:
    needs: [bump-version, build]
    runs-on: ubuntu-latest
    steps:
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.bump-version.outputs.new_ver }}
          release_name: v${{ needs.bump-version.outputs.new_ver }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

  docker-release:
    needs: [bump-version, build, python-release]
    uses: openclimatefix/.github/.github/workflows/docker-release-only.yml@v1.1.0
    with:
      image_base_name: ${{inputs.image_base_name}}
      docker_file: ${{inputs.docker_file}}
      tag_value: ${{ needs.bump-version.outputs.new_ver }}
    secrets: inherit
