name: Lint Python
on:
  workflow_call:
    inputs:
      folder:
        description: 'Folder to run checks in '
        default: '.'
        required: false
        type: string
jobs:
  run-python-linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Ruff linting
        run: |
          ruff check ${{ inputs.folder }}
      - name: Run black
        run: |
          black --line-length 100 .
