name: Python Tests
on:
  workflow_call:
    inputs:
      PYTEST-NUMCPUS:
        required: false
        type: string
        default: '2'

jobs:
  run-python-tests:
    strategy:
      matrix:
        python-version: ["3.9"]
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Do some macOS specific installs for Python 3.9
        run: |
          brew install c-blosc hdf5
        if: matrix.os == 'macos-latest'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-xdist
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install git+https://github.com/SheffieldSolar/PV_Live-API
          pip install -e .
      - name: Test with pytest
        run: |
          # lets get the string for how many cpus to use with pytest
          export PYTESTXDIST="-n $PYTEST-NUMCPUS" --dist=loadfile
          # run pytest
          pytest -s $PYTESTXDIST
