# Shortcut to run the following:
# * bump-version.yml
# * publish-to-pypi.yml
# * github-release.yml
# * push-docker.yml

name: Bump version and auto-release
on:
  workflow_call:
    secrets:
      token:
        required: true
      PAT_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      image_base_name:
        required: true
        type: string
      docker_file:
        required: false
        type: string
        default: Dockerfile

jobs:
  bump-version:
    uses: openclimatefix/.github/.github/workflows/bump-version.yml@v1.7.2
    secrets: inherit

  publish-to-pypi:
    needs: [bump-version]
    uses: openclimatefix/.github/.github/workflows/publish-to-pypi.yml@v1.2.0
    with:
      # We need this because we want to use the new commits from the `bump-version` job.
      ref: main
    secrets: inherit

  github-release:
    needs: [bump-version]
    uses: openclimatefix/.github/.github/workflows/github-release.yml@v1.2.0
    with:
      version: ${{ needs.bump-version.outputs.new_ver }}

  docker-release:
    needs: [bump-version]
    uses: openclimatefix/.github/.github/workflows/push-docker.yml@v1.2.0
    with:
      image_base_name: ${{inputs.image_base_name}}
      docker_file: ${{inputs.docker_file}}
      tag_value: ${{ needs.bump-version.outputs.new_ver }}
    secrets: inherit
